-- 01_warehouse_costs.sql
-- Calculate warehouse costs per transaction
-- Logic: Based on order characteristics (urgency, size, product category)

CREATE OR REPLACE TABLE B2B_PROFITABILITY.PUBLIC."04_WAREHOUSE_COSTS_GENERATED" AS
SELECT 
    T.TRANSACTIONID,
    T.CUSTOMERID,
    T.TRANSACTIONAMOUNT,
    T.ISSTANDARDORDER,
    T.ISURGENT,
    T.PRODUCTCATEGORY,
    
    CASE 
        WHEN T.TRANSACTIONAMOUNT > 2000 THEN ROUND(T.TRANSACTIONAMOUNT * 0.02 * 1.25, 2)
        ELSE ROUND(T.TRANSACTIONAMOUNT * 0.02, 2)
    END AS WAREHOUSE_COST_BASE,
    
    CASE WHEN T.ISURGENT THEN ROUND(T.TRANSACTIONAMOUNT * 0.02 * 0.50, 2) ELSE 0 END AS URGENT_SURCHARGE,
    
    ROUND(
        CASE 
            WHEN T.TRANSACTIONAMOUNT > 2000 THEN T.TRANSACTIONAMOUNT * 0.02 * 1.25
            ELSE T.TRANSACTIONAMOUNT * 0.02
        END +
        CASE WHEN T.ISURGENT THEN T.TRANSACTIONAMOUNT * 0.02 * 0.50 ELSE 0 END,
        2
    ) AS TOTAL_WAREHOUSE_COST
    
FROM B2B_PROFITABILITY.PUBLIC.TRANSACTIONS_GENERATED T
ORDER BY T.TRANSACTIONID
