-- 02_shipping_costs.sql
SELECT 
    T.TRANSACTIONID,
    T.CUSTOMERID,
    T.TRANSACTIONAMOUNT,
    T.ISURGENT,
    ROUND(T.TRANSACTIONAMOUNT * 0.03, 2) AS BASE_SHIPPING_COST,
    CASE WHEN T.ISURGENT THEN ROUND(T.TRANSACTIONAMOUNT * 0.03 * 1.0, 2) ELSE 0 END AS URGENT_SURCHARGE,
    CASE WHEN T.TRANSACTIONAMOUNT > 3000 THEN ROUND(T.TRANSACTIONAMOUNT * 0.03 * 0.30, 2) ELSE 0 END AS SIZE_SURCHARGE,
    ROUND(T.TRANSACTIONAMOUNT * 0.03 + CASE WHEN T.ISURGENT THEN T.TRANSACTIONAMOUNT * 0.03 * 1.0 ELSE 0 END + CASE WHEN T.TRANSACTIONAMOUNT > 3000 THEN T.TRANSACTIONAMOUNT * 0.03 * 0.30 ELSE 0 END, 2) AS TOTAL_SHIPPING_COST
FROM B2B_PROFITABILITY.PUBLIC.TRANSACTIONS_GENERATED T
ORDER BY T.TRANSACTIONID
