-- 03_admin_overhead.sql
SELECT 
    T.TRANSACTIONID,
    T.CUSTOMERID,
    T.TRANSACTIONAMOUNT,
    T.ISURGENT,
    ROUND(T.TRANSACTIONAMOUNT * 0.015, 2) AS BASE_ADMIN_COST,
    CASE WHEN T.ISURGENT THEN ROUND(T.TRANSACTIONAMOUNT * 0.015 * 0.25, 2) ELSE 0 END AS URGENT_ADMIN_SURCHARGE,
    ROUND(T.TRANSACTIONAMOUNT * 0.015 + CASE WHEN T.ISURGENT THEN T.TRANSACTIONAMOUNT * 0.015 * 0.25 ELSE 0 END, 2) AS TOTAL_ADMIN_COST
FROM B2B_PROFITABILITY.PUBLIC.TRANSACTIONS_GENERATED T
ORDER BY T.TRANSACTIONID
