-- 04_financial_pl.sql
SELECT 
    T.TRANSACTIONID,
    T.CUSTOMERID,
    T.TRANSACTIONAMOUNT AS REVENUE,
    ROUND(T.TRANSACTIONAMOUNT * 0.02, 2) + CASE WHEN T.TRANSACTIONAMOUNT > 2000 THEN ROUND(T.TRANSACTIONAMOUNT * 0.02 * 1.25, 2) ELSE 0 END + CASE WHEN T.ISURGENT THEN ROUND(T.TRANSACTIONAMOUNT * 0.02 * 0.50, 2) ELSE 0 END AS WAREHOUSE_COST,
    ROUND(T.TRANSACTIONAMOUNT * 0.03, 2) + CASE WHEN T.ISURGENT THEN ROUND(T.TRANSACTIONAMOUNT * 0.03 * 1.0, 2) ELSE 0 END + CASE WHEN T.TRANSACTIONAMOUNT > 3000 THEN ROUND(T.TRANSACTIONAMOUNT * 0.03 * 0.30, 2) ELSE 0 END AS SHIPPING_COST,
    ROUND(T.TRANSACTIONAMOUNT * 0.015, 2) + CASE WHEN T.ISURGENT THEN ROUND(T.TRANSACTIONAMOUNT * 0.015 * 0.25, 2) ELSE 0 END AS ADMIN_COST,
    ROUND(T.TRANSACTIONAMOUNT * 0.35, 2) AS COGS,
    ROUND(T.TRANSACTIONAMOUNT - (ROUND(T.TRANSACTIONAMOUNT * 0.02, 2) + CASE WHEN T.TRANSACTIONAMOUNT > 2000 THEN ROUND(T.TRANSACTIONAMOUNT * 0.02 * 1.25, 2) ELSE 0 END + CASE WHEN T.ISURGENT THEN ROUND(T.TRANSACTIONAMOUNT * 0.02 * 0.50, 2) ELSE 0 END) - (ROUND(T.TRANSACTIONAMOUNT * 0.03, 2) + CASE WHEN T.ISURGENT THEN ROUND(T.TRANSACTIONAMOUNT * 0.03 * 1.0, 2) ELSE 0 END + CASE WHEN T.TRANSACTIONAMOUNT > 3000 THEN ROUND(T.TRANSACTIONAMOUNT * 0.03 * 0.30, 2) ELSE 0 END) - (ROUND(T.TRANSACTIONAMOUNT * 0.015, 2) + CASE WHEN T.ISURGENT THEN ROUND(T.TRANSACTIONAMOUNT * 0.015 * 0.25, 2) ELSE 0 END) - ROUND(T.TRANSACTIONAMOUNT * 0.35, 2), 2) AS NET_PROFIT
FROM B2B_PROFITABILITY.PUBLIC.TRANSACTIONS_GENERATED T
ORDER BY T.TRANSACTIONID
