-- 05_customer_clv.sql
SELECT 
    C.CUSTOMERID,
    C.CUSTOMERNAME,
    COUNT(T.TRANSACTIONID) AS TOTAL_TRANSACTIONS,
    ROUND(SUM(T.TRANSACTIONAMOUNT), 2) AS TOTAL_REVENUE,
    ROUND(AVG(T.TRANSACTIONAMOUNT), 2) AS AVG_ORDER_VALUE,
    ROUND(SUM(T.TRANSACTIONAMOUNT - (ROUND(T.TRANSACTIONAMOUNT * 0.02, 2) + CASE WHEN T.TRANSACTIONAMOUNT > 2000 THEN ROUND(T.TRANSACTIONAMOUNT * 0.02 * 1.25, 2) ELSE 0 END + CASE WHEN T.ISURGENT THEN ROUND(T.TRANSACTIONAMOUNT * 0.02 * 0.50, 2) ELSE 0 END) - (ROUND(T.TRANSACTIONAMOUNT * 0.03, 2) + CASE WHEN T.ISURGENT THEN ROUND(T.TRANSACTIONAMOUNT * 0.03 * 1.0, 2) ELSE 0 END + CASE WHEN T.TRANSACTIONAMOUNT > 3000 THEN ROUND(T.TRANSACTIONAMOUNT * 0.03 * 0.30, 2) ELSE 0 END) - (ROUND(T.TRANSACTIONAMOUNT * 0.015, 2) + CASE WHEN T.ISURGENT THEN ROUND(T.TRANSACTIONAMOUNT * 0.015 * 0.25, 2) ELSE 0 END) - ROUND(T.TRANSACTIONAMOUNT * 0.35, 2)), 2) AS TOTAL_CUSTOMER_PROFIT,
    ROUND(SUM(T.TRANSACTIONAMOUNT - (ROUND(T.TRANSACTIONAMOUNT * 0.02, 2) + CASE WHEN T.TRANSACTIONAMOUNT > 2000 THEN ROUND(T.TRANSACTIONAMOUNT * 0.02 * 1.25, 2) ELSE 0 END + CASE WHEN T.ISURGENT THEN ROUND(T.TRANSACTIONAMOUNT * 0.02 * 0.50, 2) ELSE 0 END) - (ROUND(T.TRANSACTIONAMOUNT * 0.03, 2) + CASE WHEN T.ISURGENT THEN ROUND(T.TRANSACTIONAMOUNT * 0.03 * 1.0, 2) ELSE 0 END + CASE WHEN T.TRANSACTIONAMOUNT > 3000 THEN ROUND(T.TRANSACTIONAMOUNT * 0.03 * 0.30, 2) ELSE 0 END) - (ROUND(T.TRANSACTIONAMOUNT * 0.015, 2) + CASE WHEN T.ISURGENT THEN ROUND(T.TRANSACTIONAMOUNT * 0.015 * 0.25, 2) ELSE 0 END) - ROUND(T.TRANSACTIONAMOUNT * 0.35, 2)) * COUNT(T.TRANSACTIONID) / 100, 2) AS CLV_SCORE
FROM B2B_PROFITABILITY.PUBLIC.CUSTOMER_MASTER C
LEFT JOIN B2B_PROFITABILITY.PUBLIC.TRANSACTIONS_GENERATED T ON C.CUSTOMERID = T.CUSTOMERID
GROUP BY C.CUSTOMERID, C.CUSTOMERNAME
ORDER BY TOTAL_CUSTOMER_PROFIT DESC
