-- 06_returns_handling.sql
SELECT 
    T.TRANSACTIONID,
    T.CUSTOMERID,
    T.TRANSACTIONAMOUNT,
    CASE WHEN MOD(CAST(SUBSTR(T.TRANSACTIONID, -3) AS INT), 20) = 0 THEN TRUE ELSE FALSE END AS HAS_RETURN,
    CASE 
        WHEN MOD(CAST(SUBSTR(T.TRANSACTIONID, -3) AS INT), 20) = 0 THEN ROUND(T.TRANSACTIONAMOUNT * 0.05, 2)
        ELSE 0 
    END AS RETURN_PROCESSING_COST,
    CASE 
        WHEN MOD(CAST(SUBSTR(T.TRANSACTIONID, -3) AS INT), 20) = 0 THEN ROUND(T.TRANSACTIONAMOUNT * 0.08, 2)
        ELSE 0 
    END AS RETURN_SHIPPING_COST,
    CASE 
        WHEN MOD(CAST(SUBSTR(T.TRANSACTIONID, -3) AS INT), 20) = 0 THEN ROUND(T.TRANSACTIONAMOUNT * 0.02, 2)
        ELSE 0 
    END AS RESTOCKING_COST,
    CASE 
        WHEN MOD(CAST(SUBSTR(T.TRANSACTIONID, -3) AS INT), 20) = 0 THEN ROUND(T.TRANSACTIONAMOUNT * 0.15, 2)
        ELSE 0 
    END AS TOTAL_RETURN_COST
FROM B2B_PROFITABILITY.PUBLIC.TRANSACTIONS_GENERATED T
ORDER BY T.TRANSACTIONID
