-- 07_payment_terms_interest.sql
SELECT 
    T.TRANSACTIONID,
    T.CUSTOMERID,
    T.TRANSACTIONAMOUNT,
    CASE WHEN MOD(CAST(SUBSTR(T.TRANSACTIONID, -2) AS INT), 3) = 0 THEN 30 ELSE 0 END AS PAYMENT_TERMS_DAYS,
    CASE WHEN MOD(CAST(SUBSTR(T.TRANSACTIONID, -2) AS INT), 3) = 0 THEN ROUND(T.TRANSACTIONAMOUNT * 0.06 / 365 * 30, 2) ELSE 0 END AS INTEREST_COST,
    CASE WHEN MOD(CAST(SUBSTR(T.TRANSACTIONID, -2) AS INT), 10) = 0 THEN ROUND(T.TRANSACTIONAMOUNT * 0.02, 2) ELSE 0 END AS LATE_PAYMENT_RISK,
    ROUND(
        CASE WHEN MOD(CAST(SUBSTR(T.TRANSACTIONID, -2) AS INT), 3) = 0 THEN T.TRANSACTIONAMOUNT * 0.06 / 365 * 30 ELSE 0 END +
        CASE WHEN MOD(CAST(SUBSTR(T.TRANSACTIONID, -2) AS INT), 10) = 0 THEN T.TRANSACTIONAMOUNT * 0.02 ELSE 0 END,
        2
    ) AS TOTAL_FINANCING_COST
FROM B2B_PROFITABILITY.PUBLIC.TRANSACTIONS_GENERATED T
ORDER BY T.TRANSACTIONID
