-- 08_scenario_planning.sql - SCENARIO ANALYSIS
-- Based on Dataset 10 P&L calculations
-- Three scenarios: Base / Optimistic / Pessimistic

CREATE OR REPLACE TABLE B2B_PROFITABILITY.PUBLIC."08_SCENARIO_PLANNING_GENERATED" AS
SELECT 
    PL.TRANSACTIONID,
    PL.CUSTOMERID,
    PL.CUSTOMERSEGMENT,
    PL.TRANSACTIONAMOUNT AS BASE_REVENUE,
    
    -- STEP 1: SCENARIO REVENUES
    ROUND(PL.TRANSACTIONAMOUNT * 1.15, 2) AS OPTIMISTIC_REVENUE,
    ROUND(PL.TRANSACTIONAMOUNT * 0.85, 2) AS PESSIMISTIC_REVENUE,
    
    -- STEP 2: BASE SCENARIO COSTS
    PL.TOTALCOST_EUR AS BASE_TOTAL_COST,
    
    -- STEP 3: OPTIMISTIC COSTS (-25% = multiply by 0.75)
    ROUND(PL.TOTALCOST_EUR * 0.75, 2) AS OPTIMISTIC_TOTAL_COST,
    
    -- STEP 4: PESSIMISTIC COSTS (+50% = multiply by 1.50)
    ROUND(PL.TOTALCOST_EUR * 1.50, 2) AS PESSIMISTIC_TOTAL_COST,
    
    -- STEP 5: BASE PROFIT
    PL.PROFIT_EUR AS BASE_PROFIT,
    
    -- STEP 6: OPTIMISTIC PROFIT
    ROUND((PL.TRANSACTIONAMOUNT * 1.15) - (PL.TOTALCOST_EUR * 0.75), 2) AS OPTIMISTIC_PROFIT,
    
    -- STEP 7: PESSIMISTIC PROFIT
    ROUND((PL.TRANSACTIONAMOUNT * 0.85) - (PL.TOTALCOST_EUR * 1.50), 2) AS PESSIMISTIC_PROFIT
    
FROM B2B_PROFITABILITY.PUBLIC."10_FINANCIAL_P_L_ORDERS" PL
ORDER BY PL.TRANSACTIONID
