-- 08_scenario_planning.sql
SELECT 
    T.TRANSACTIONID,
    T.CUSTOMERID,
    T.TRANSACTIONAMOUNT AS BASE_REVENUE,
    ROUND(T.TRANSACTIONAMOUNT * 1.15, 2) AS OPTIMISTIC_SCENARIO_REVENUE,
    ROUND(T.TRANSACTIONAMOUNT * 0.85, 2) AS PESSIMISTIC_SCENARIO_REVENUE,
    ROUND(T.TRANSACTIONAMOUNT * 0.02, 2) AS BASE_COST,
    ROUND(T.TRANSACTIONAMOUNT * 0.02 * 1.25, 2) AS OPTIMISTIC_COST,
    ROUND(T.TRANSACTIONAMOUNT * 0.02 * 1.50, 2) AS PESSIMISTIC_COST,
    ROUND(T.TRANSACTIONAMOUNT - (T.TRANSACTIONAMOUNT * 0.02 + T.TRANSACTIONAMOUNT * 0.03 + T.TRANSACTIONAMOUNT * 0.015 + T.TRANSACTIONAMOUNT * 0.35), 2) AS BASE_PROFIT,
    ROUND((T.TRANSACTIONAMOUNT * 1.15) - ((T.TRANSACTIONAMOUNT * 0.02 * 1.25) + (T.TRANSACTIONAMOUNT * 0.03) + (T.TRANSACTIONAMOUNT * 0.015) + (T.TRANSACTIONAMOUNT * 0.35)), 2) AS OPTIMISTIC_PROFIT,
    ROUND((T.TRANSACTIONAMOUNT * 0.85) - ((T.TRANSACTIONAMOUNT * 0.02 * 1.50) + (T.TRANSACTIONAMOUNT * 0.03) + (T.TRANSACTIONAMOUNT * 0.015) + (T.TRANSACTIONAMOUNT * 0.35)), 2) AS PESSIMISTIC_PROFIT
FROM B2B_PROFITABILITY.PUBLIC.TRANSACTIONS_GENERATED T
ORDER BY T.TRANSACTIONID
