-- 10_financial_pnl.sql - COMPLETE COST-TO-SERVE ANALYSIS
-- Combines all datasets: Revenue - All Costs = Profit
-- Includes action flags for pricing/cost decisions

SELECT 
    T.TRANSACTIONID,
    T.CUSTOMERID,
    C.CUSTOMERSEGMENT,
    T.PRODUCTCATEGORY,
    T.ORDERMONTH,
    P.PAYMENTTERMS,
    T.ISSTANDARDORDER,
    T.ISURGENT,
    
    -- STEP 1: REVENUE
    ROUND(T.TRANSACTIONAMOUNT, 2) AS TRANSACTIONAMOUNT,
    
    -- STEP 2: COST COMPONENTS (from Datasets 4-7, 9)
    ROUND(T.TRANSACTIONAMOUNT * 0.60, 2) AS COGS_EUR,
    ROUND(W.TOTALWAREHOUSEOPERATIONSCOST_EUR, 2) AS WAREHOUSECOST_EUR,
    ROUND(S.TOTALSHIPPINGCOST_EUR, 2) AS SHIPPINGCOST_EUR,
    ROUND(R.TOTALRETURNEXPENSE_EUR, 2) AS RETURNSCOST_EUR,
    ROUND(P.DSO_INTERESTCOST_EUR, 2) AS INTERESTCOST_EUR,
    ROUND(O.TOTALALLOCATEDOVERHEAD_EUR, 2) AS OVERHEADCOST_EUR,
    
    -- STEP 3: TOTAL COST-TO-SERVE
    ROUND(
        (T.TRANSACTIONAMOUNT * 0.60) +
        COALESCE(W.TOTALWAREHOUSEOPERATIONSCOST_EUR, 0) +
        COALESCE(S.TOTALSHIPPINGCOST_EUR, 0) +
        COALESCE(R.TOTALRETURNEXPENSE_EUR, 0) +
        COALESCE(P.DSO_INTERESTCOST_EUR, 0) +
        COALESCE(O.TOTALALLOCATEDOVERHEAD_EUR, 0),
        2
    ) AS TOTALCOST_EUR,
    
    -- STEP 4: PROFIT
    ROUND(
        T.TRANSACTIONAMOUNT - 
        ((T.TRANSACTIONAMOUNT * 0.60) +
         COALESCE(W.TOTALWAREHOUSEOPERATIONSCOST_EUR, 0) +
         COALESCE(S.TOTALSHIPPINGCOST_EUR, 0) +
         COALESCE(R.TOTALRETURNEXPENSE_EUR, 0) +
         COALESCE(P.DSO_INTERESTCOST_EUR, 0) +
         COALESCE(O.TOTALALLOCATEDOVERHEAD_EUR, 0)),
        2
    ) AS PROFIT_EUR,
    
    -- STEP 5: PROFIT MARGIN %
    ROUND(
        (T.TRANSACTIONAMOUNT - 
         ((T.TRANSACTIONAMOUNT * 0.60) +
          COALESCE(W.TOTALWAREHOUSEOPERATIONSCOST_EUR, 0) +
          COALESCE(S.TOTALSHIPPINGCOST_EUR, 0) +
          COALESCE(R.TOTALRETURNEXPENSE_EUR, 0) +
          COALESCE(P.DSO_INTERESTCOST_EUR, 0) +
          COALESCE(O.TOTALALLOCATEDOVERHEAD_EUR, 0))) / T.TRANSACTIONAMOUNT * 100,
        2
    ) AS PROFITMARGIN_PCT,
    
    -- STEP 6: COST AS % OF REVENUE
    ROUND(
        ((T.TRANSACTIONAMOUNT * 0.60) +
         COALESCE(W.TOTALWAREHOUSEOPERATIONSCOST_EUR, 0) +
         COALESCE(S.TOTALSHIPPINGCOST_EUR, 0) +
         COALESCE(R.TOTALRETURNEXPENSE_EUR, 0) +
         COALESCE(P.DSO_INTERESTCOST_EUR, 0) +
         COALESCE(O.TOTALALLOCATEDOVERHEAD_EUR, 0)) / T.TRANSACTIONAMOUNT * 100,
        2
    ) AS COSTTOREVENUE_PCT,
    
    -- STEP 7: PROFITABILITY CATEGORY
    CASE 
        WHEN (T.TRANSACTIONAMOUNT - 
              ((T.TRANSACTIONAMOUNT * 0.60) +
               COALESCE(W.TOTALWAREHOUSEOPERATIONSCOST_EUR, 0) +
               COALESCE(S.TOTALSHIPPINGCOST_EUR, 0) +
               COALESCE(R.TOTALRETURNEXPENSE_EUR, 0) +
               COALESCE(P.DSO_INTERESTCOST_EUR, 0) +
               COALESCE(O.TOTALALLOCATEDOVERHEAD_EUR, 0))) > 50 THEN 'Highly Profitable'
        WHEN (T.TRANSACTIONAMOUNT - 
              ((T.TRANSACTIONAMOUNT * 0.60) +
               COALESCE(W.TOTALWAREHOUSEOPERATIONSCOST_EUR, 0) +
               COALESCE(S.TOTALSHIPPINGCOST_EUR, 0) +
               COALESCE(R.TOTALRETURNEXPENSE_EUR, 0) +
               COALESCE(P.DSO_INTERESTCOST_EUR, 0) +
               COALESCE(O.TOTALALLOCATEDOVERHEAD_EUR, 0))) > 0 THEN 'Profitable'
        WHEN (T.TRANSACTIONAMOUNT - 
              ((T.TRANSACTIONAMOUNT * 0.60) +
               COALESCE(W.TOTALWAREHOUSEOPERATIONSCOST_EUR, 0) +
               COALESCE(S.TOTALSHIPPINGCOST_EUR, 0) +
               COALESCE(R.TOTALRETURNEXPENSE_EUR, 0) +
               COALESCE(P.DSO_INTERESTCOST_EUR, 0) +
               COALESCE(O.TOTALALLOCATEDOVERHEAD_EUR, 0))) > -25 THEN 'Breakeven'
        ELSE 'Loss'
    END AS PROFITABILITYCATEGORY,
    
    -- STEP 8: ACTION FLAGS
    CASE 
        WHEN (T.TRANSACTIONAMOUNT - 
              ((T.TRANSACTIONAMOUNT * 0.60) +
               COALESCE(W.TOTALWAREHOUSEOPERATIONSCOST_EUR, 0) +
               COALESCE(S.TOTALSHIPPINGCOST_EUR, 0) +
               COALESCE(R.TOTALRETURNEXPENSE_EUR, 0) +
               COALESCE(P.DSO_INTERESTCOST_EUR, 0) +
               COALESCE(O.TOTALALLOCATEDOVERHEAD_EUR, 0))) < 0 THEN TRUE
        ELSE FALSE
    END AS SHOULDRAISEPRICE,
    
    CASE 
        WHEN (((T.TRANSACTIONAMOUNT * 0.60) +
               COALESCE(W.TOTALWAREHOUSEOPERATIONSCOST_EUR, 0) +
               COALESCE(S.TOTALSHIPPINGCOST_EUR, 0) +
               COALESCE(R.TOTALRETURNEXPENSE_EUR, 0) +
               COALESCE(P.DSO_INTERESTCOST_EUR, 0) +
               COALESCE(O.TOTALALLOCATEDOVERHEAD_EUR, 0)) / T.TRANSACTIONAMOUNT * 100) > 95 THEN TRUE
        ELSE FALSE
    END AS SHOULDREDUCECOST,
    
    CASE 
        WHEN (T.TRANSACTIONAMOUNT - 
              ((T.TRANSACTIONAMOUNT * 0.60) +
               COALESCE(W.TOTALWAREHOUSEOPERATIONSCOST_EUR, 0) +
               COALESCE(S.TOTALSHIPPINGCOST_EUR, 0) +
               COALESCE(R.TOTALRETURNEXPENSE_EUR, 0) +
               COALESCE(P.DSO_INTERESTCOST_EUR, 0) +
               COALESCE(O.TOTALALLOCATEDOVERHEAD_EUR, 0))) < 0 OR
             (((T.TRANSACTIONAMOUNT * 0.60) +
               COALESCE(W.TOTALWAREHOUSEOPERATIONSCOST_EUR, 0) +
               COALESCE(S.TOTALSHIPPINGCOST_EUR, 0) +
               COALESCE(R.TOTALRETURNEXPENSE_EUR, 0) +
               COALESCE(P.DSO_INTERESTCOST_EUR, 0) +
               COALESCE(O.TOTALALLOCATEDOVERHEAD_EUR, 0)) / T.TRANSACTIONAMOUNT * 100) > 95 THEN TRUE
        ELSE FALSE
    END AS SHOULDREVIEWCUSTOMER
    
FROM B2B_PROFITABILITY.PUBLIC.TRANSACTIONS_GENERATED T
JOIN B2B_PROFITABILITY.PUBLIC.CUSTOMER_MASTER C ON T.CUSTOMERID = C.CUSTOMERID
LEFT JOIN B2B_PROFITABILITY.PUBLIC.04_WAREHOUSE_COSTS_GENERATED W ON T.TRANSACTIONID = W.TRANSACTIONID
LEFT JOIN B2B_PROFITABILITY.PUBLIC.05_SHIPPING_COSTS_GENERATED S ON T.TRANSACTIONID = S.TRANSACTIONID
LEFT JOIN B2B_PROFITABILITY.PUBLIC.06_RETURNS_HANDLING_GENERATED R ON T.TRANSACTIONID = R.TRANSACTIONID
LEFT JOIN B2B_PROFITABILITY.PUBLIC.07_PAYMENT_TERMS_INTEREST_GENERATED P ON T.TRANSACTIONID = P.TRANSACTIONID
LEFT JOIN B2B_PROFITABILITY.PUBLIC.09_ADMIN_OVERHEAD_GENERATED O ON T.TRANSACTIONID = O.TRANSACTIONID
ORDER BY T.TRANSACTIONID
