-- 14_scenario_summary.sql - SCENARIO PLANNING SUMMARY (simplified aggregation)
-- Strategic what-if analysis aggregation
-- Note: Full scenario modeling requires Python (customer filtering + recalculations)

-- This query shows key metrics for strategic decisions
SELECT 
    'Scenario Analysis' AS ANALYSISTYPE,
    COUNT(DISTINCT CUSTOMERID) AS TOTAL_CUSTOMERS,
    ROUND(SUM(TRANSACTIONAMOUNT), 2) AS TOTAL_REVENUE,
    ROUND(SUM(TOTALCOST_EUR), 2) AS TOTAL_COSTS,
    ROUND(SUM(PROFIT_EUR), 2) AS TOTAL_PROFIT,
    ROUND((SUM(PROFIT_EUR) / SUM(TRANSACTIONAMOUNT)) * 100, 2) AS OVERALL_MARGIN_PCT,
    
    -- A-Customers analysis
    (SELECT COUNT(DISTINCT CUSTOMERID) FROM B2B_PROFITABILITY.PUBLIC.11_CUSTOMER_LIFETIME_VALUE WHERE CLVSEGMENT = 'A-Customer') AS A_CUSTOMER_COUNT,
    (SELECT ROUND(SUM(CLV_EUR), 2) FROM B2B_PROFITABILITY.PUBLIC.11_CUSTOMER_LIFETIME_VALUE WHERE CLVSEGMENT = 'A-Customer') AS A_CUSTOMER_TOTAL_CLV,
    
    -- B-Customers analysis
    (SELECT COUNT(DISTINCT CUSTOMERID) FROM B2B_PROFITABILITY.PUBLIC.11_CUSTOMER_LIFETIME_VALUE WHERE CLVSEGMENT = 'B-Customer') AS B_CUSTOMER_COUNT,
    (SELECT ROUND(SUM(CLV_EUR), 2) FROM B2B_PROFITABILITY.PUBLIC.11_CUSTOMER_LIFETIME_VALUE WHERE CLVSEGMENT = 'B-Customer') AS B_CUSTOMER_TOTAL_CLV,
    
    -- C-Customers analysis
    (SELECT COUNT(DISTINCT CUSTOMERID) FROM B2B_PROFITABILITY.PUBLIC.11_CUSTOMER_LIFETIME_VALUE WHERE CLVSEGMENT = 'C-Customer') AS C_CUSTOMER_COUNT,
    (SELECT ROUND(SUM(CLV_EUR), 2) FROM B2B_PROFITABILITY.PUBLIC.11_CUSTOMER_LIFETIME_VALUE WHERE CLVSEGMENT = 'C-Customer') AS C_CUSTOMER_TOTAL_CLV
    
FROM B2B_PROFITABILITY.PUBLIC.10_FINANCIAL_P_L_ORDERS
